### ISSUE TITLE
Proper description not provided

### ISSUE THREAD

**Issue by nitinkumar30** [patilanirudh/Slack_bot#1]
Some descriptions like where to put .env file, what are the required libraries to install, where can we get tokens to use in slack etc.

**Comment by patilanirudh** [comment]
Thank you for the input ! Will make the changes!!

**Comment by nitinkumar30** [comment]
I've created [my repo](https://github.com/nitinkumar30/slack_chatBot) with proper description. You can take help or directly use it here.
